"""Cloud region coordinates and US city name lists for proximity features."""

from __future__ import annotations

CLOUD_REGIONS: list[dict[str, str | float]] = [
    {"provider": "AWS", "region": "us-east-1", "name": "N. Virginia", "lat": 38.9519, "lon": -77.4480},
    {"provider": "AWS", "region": "us-east-2", "name": "Ohio", "lat": 40.4173, "lon": -82.9071},
    {"provider": "AWS", "region": "us-west-1", "name": "N. California", "lat": 37.3861, "lon": -122.0839},
    {"provider": "AWS", "region": "us-west-2", "name": "Oregon", "lat": 45.5231, "lon": -122.6765},
    {"provider": "AWS", "region": "us-gov-west-1", "name": "GovCloud West", "lat": 45.8491, "lon": -119.7143},
    {"provider": "AWS", "region": "us-gov-east-1", "name": "GovCloud East", "lat": 38.9519, "lon": -77.4480},
    {"provider": "Azure", "region": "eastus", "name": "Virginia", "lat": 37.3719, "lon": -79.8164},
    {"provider": "Azure", "region": "eastus2", "name": "Virginia 2", "lat": 36.6681, "lon": -78.3889},
    {"provider": "Azure", "region": "centralus", "name": "Iowa", "lat": 41.5908, "lon": -93.6208},
    {"provider": "Azure", "region": "northcentralus", "name": "Illinois", "lat": 41.8500, "lon": -88.0000},
    {"provider": "Azure", "region": "southcentralus", "name": "Texas", "lat": 29.4167, "lon": -98.5000},
    {"provider": "Azure", "region": "westcentralus", "name": "Wyoming", "lat": 40.8900, "lon": -110.3340},
    {"provider": "Azure", "region": "westus", "name": "California", "lat": 37.7833, "lon": -122.4167},
    {"provider": "Azure", "region": "westus2", "name": "Washington", "lat": 47.2330, "lon": -119.8520},
    {"provider": "Azure", "region": "westus3", "name": "Arizona", "lat": 33.4484, "lon": -112.0740},
    {"provider": "GCP", "region": "us-east1", "name": "S. Carolina", "lat": 33.1960, "lon": -80.0131},
    {"provider": "GCP", "region": "us-east4", "name": "N. Virginia", "lat": 38.9519, "lon": -77.4480},
    {"provider": "GCP", "region": "us-east5", "name": "Columbus OH", "lat": 39.9612, "lon": -82.9988},
    {"provider": "GCP", "region": "us-central1", "name": "Iowa", "lat": 41.2619, "lon": -95.8608},
    {"provider": "GCP", "region": "us-west1", "name": "Oregon", "lat": 45.5946, "lon": -121.1787},
    {"provider": "GCP", "region": "us-west2", "name": "Los Angeles", "lat": 34.0522, "lon": -118.2437},
    {"provider": "GCP", "region": "us-west3", "name": "Salt Lake City", "lat": 40.7608, "lon": -111.8910},
    {"provider": "GCP", "region": "us-west4", "name": "Las Vegas", "lat": 36.1699, "lon": -115.1398},
    {"provider": "GCP", "region": "us-south1", "name": "Dallas", "lat": 32.7767, "lon": -96.7970},
]


CITIES_50K: frozenset[str] = frozenset({
    "Abilene",
    "Akron",
    "Alameda",
    "Albany",
    "Albuquerque",
    "Alexandria",
    "Alhambra",
    "Aliso Viejo",
    "Allen",
    "Allentown",
    "Alpharetta",
    "Amarillo",
    "Ames",
    "Anaheim",
    "Anchorage",
    "Anderson",
    "Ankeny",
    "Ann Arbor",
    "Antioch",
    "Apple Valley",
    "Appleton",
    "Arcadia",
    "Arlington",
    "Arlington Heights",
    "Arvada",
    "Asheville",
    "Athens-Clarke County",
    "Atlanta",
    "Auburn",
    "Augusta-Richmond County",
    "Aurora",
    "Austin",
    "Avondale",
    "Bakersfield",
    "Baldwin Park",
    "Baltimore",
    "Bartlett",
    "Baton Rouge",
    "Battle Creek",
    "Bayonne",
    "Baytown",
    "Beaumont",
    "Beaverton",
    "Bellevue",
    "Bellflower",
    "Bellingham",
    "Bend",
    "Berkeley",
    "Berwyn",
    "Bethlehem",
    "Billings",
    "Birmingham",
    "Bismarck",
    "Blaine",
    "Bloomington",
    "Blue Springs",
    "Boca Raton",
    "Boise City",
    "Bolingbrook",
    "Bossier City",
    "Boston",
    "Boulder",
    "Bowie",
    "Bowling Green",
    "Boynton Beach",
    "Bradenton",
    "Brentwood",
    "Bridgeport",
    "Bristol",
    "Brockton",
    "Broken Arrow",
    "Brookhaven",
    "Brooklyn Park",
    "Broomfield",
    "Brownsville",
    "Bryan",
    "Buckeye",
    "Buena Park",
    "Buffalo",
    "Burbank",
    "Burlington",
    "Burnsville",
    "Camarillo",
    "Cambridge",
    "Camden",
    "Canton",
    "Cape Coral",
    "Carlsbad",
    "Carmel",
    "Carrollton",
    "Carson",
    "Carson City",
    "Cary",
    "Casa Grande",
    "Casper",
    "Castle Rock",
    "Cathedral City",
    "Cedar Park",
    "Cedar Rapids",
    "Centennial",
    "Champaign",
    "Chandler",
    "Chapel Hill",
    "Charleston",
    "Charlotte",
    "Chattanooga",
    "Chesapeake",
    "Cheyenne",
    "Chicago",
    "Chico",
    "Chicopee",
    "Chino",
    "Chino Hills",
    "Chula Vista",
    "Cicero",
    "Cincinnati",
    "Citrus Heights",
    "Clarksville",
    "Clearwater",
    "Cleveland",
    "Clifton",
    "Clovis",
    "Coconut Creek",
    "College Station",
    "Colorado Springs",
    "Colton",
    "Columbia",
    "Columbus",
    "Compton",
    "Concord",
    "Conroe",
    "Conway",
    "Coon Rapids",
    "Coral Springs",
    "Corona",
    "Corpus Christi",
    "Corvallis",
    "Costa Mesa",
    "Council Bluffs",
    "Cranston",
    "Cupertino",
    "Dallas",
    "Daly City",
    "Danbury",
    "Davenport",
    "Davie",
    "Davis",
    "Dayton",
    "Daytona Beach",
    "DeSoto",
    "Dearborn",
    "Dearborn Heights",
    "Decatur",
    "Deerfield Beach",
    "Delano",
    "Delray Beach",
    "Deltona",
    "Denton",
    "Denver",
    "Des Moines",
    "Des Plaines",
    "Detroit",
    "Diamond Bar",
    "Doral",
    "Dothan",
    "Downey",
    "Dublin",
    "Dubuque",
    "Duluth",
    "Durham",
    "Eagan",
    "East Orange",
    "Eastvale",
    "Eau Claire",
    "Eden Prairie",
    "Edinburg",
    "Edmond",
    "El Cajon",
    "El Monte",
    "El Paso",
    "Elgin",
    "Elizabeth",
    "Elk Grove",
    "Elkhart",
    "Elyria",
    "Encinitas",
    "Enid",
    "Erie",
    "Escondido",
    "Eugene",
    "Euless",
    "Evanston",
    "Evansville",
    "Everett",
    "Fairfield",
    "Fall River",
    "Fargo",
    "Farmington Hills",
    "Fayetteville",
    "Federal Way",
    "Fishers",
    "Flagstaff",
    "Flint",
    "Florissant",
    "Flower Mound",
    "Folsom",
    "Fontana",
    "Fort Collins",
    "Fort Lauderdale",
    "Fort Myers",
    "Fort Smith",
    "Fort Wayne",
    "Fort Worth",
    "Fountain Valley",
    "Franklin",
    "Frederick",
    "Fremont",
    "Fresno",
    "Frisco",
    "Fullerton",
    "Gainesville",
    "Gaithersburg",
    "Garden Grove",
    "Gardena",
    "Garland",
    "Gary",
    "Gastonia",
    "Georgetown",
    "Gilbert",
    "Gilroy",
    "Glendale",
    "Glendora",
    "Goodyear",
    "Grand Forks",
    "Grand Island",
    "Grand Junction",
    "Grand Prairie",
    "Grand Rapids",
    "Grapevine",
    "Great Falls",
    "Greeley",
    "Green Bay",
    "Greensboro",
    "Greenville",
    "Greenwood",
    "Gresham",
    "Gulfport",
    "Hamilton",
    "Hammond",
    "Hampton",
    "Hanford",
    "Harlingen",
    "Harrisonburg",
    "Hartford",
    "Haverhill",
    "Hawthorne",
    "Hayward",
    "Hemet",
    "Hempstead",
    "Henderson",
    "Hendersonville",
    "Hesperia",
    "Hialeah",
    "High Point",
    "Highland",
    "Hillsboro",
    "Hoboken",
    "Hoffman Estates",
    "Hollywood",
    "Homestead",
    "Honolulu",
    "Hoover",
    "Houston",
    "Huntersville",
    "Huntington Beach",
    "Huntington Park",
    "Huntsville",
    "Idaho Falls",
    "Independence",
    "Indianapolis",
    "Indio",
    "Inglewood",
    "Iowa City",
    "Irvine",
    "Irving",
    "Jackson",
    "Jacksonville",
    "Janesville",
    "Jersey City",
    "Johns Creek",
    "Johnson City",
    "Joliet",
    "Jonesboro",
    "Joplin",
    "Jupiter",
    "Jurupa Valley",
    "Kalamazoo",
    "Kansas City",
    "Kenner",
    "Kennewick",
    "Kenosha",
    "Kent",
    "Kentwood",
    "Kettering",
    "Killeen",
    "Kingsport",
    "Kirkland",
    "Kissimmee",
    "Knoxville",
    "Kokomo",
    "La Crosse",
    "La Habra",
    "La Mesa",
    "Lafayette",
    "Laguna Niguel",
    "Lake Charles",
    "Lake Elsinore",
    "Lake Forest",
    "Lake Havasu City",
    "Lakeland",
    "Lakeville",
    "Lakewood",
    "Lancaster",
    "Lansing",
    "Laredo",
    "Largo",
    "Las Cruces",
    "Las Vegas",
    "Lauderhill",
    "Lawrence",
    "Lawton",
    "Layton",
    "League City",
    "Lee's Summit",
    "Lehi",
    "Lenexa",
    "Lewisville",
    "Lexington-Fayette",
    "Lincoln",
    "Little Rock",
    "Livermore",
    "Livonia",
    "Lodi",
    "Long Beach",
    "Longmont",
    "Longview",
    "Lorain",
    "Los Angeles",
    "Louisville",
    "Loveland",
    "Lowell",
    "Lubbock",
    "Lynchburg",
    "Lynn",
    "Lynwood",
    "Macon",
    "Madera",
    "Madison",
    "Malden",
    "Manchester",
    "Manhattan",
    "Mansfield",
    "Manteca",
    "Maple Grove",
    "Margate",
    "Marietta",
    "Marysville",
    "McAllen",
    "McKinney",
    "Medford",
    "Melbourne",
    "Memphis",
    "Menifee",
    "Merced",
    "Meriden",
    "Meridian",
    "Mesa",
    "Mesquite",
    "Miami",
    "Miami Beach",
    "Miami Gardens",
    "Midland",
    "Midwest City",
    "Milford",
    "Milpitas",
    "Milwaukee",
    "Minneapolis",
    "Minnetonka",
    "Miramar",
    "Mission",
    "Mission Viejo",
    "Missoula",
    "Missouri City",
    "Mobile",
    "Modesto",
    "Montebello",
    "Monterey Park",
    "Montgomery",
    "Moore",
    "Moreno Valley",
    "Mount Pleasant",
    "Mount Prospect",
    "Mount Vernon",
    "Mountain View",
    "Muncie",
    "Murfreesboro",
    "Murrieta",
    "Nampa",
    "Napa",
    "Naperville",
    "Nashua",
    "Nashville",
    "National City",
    "New Bedford",
    "New Braunfels",
    "New Britain",
    "New Brunswick",
    "New Haven",
    "New Orleans",
    "New Rochelle",
    "New York",
    "Newark",
    "Newport Beach",
    "Newport News",
    "Newton",
    "Noblesville",
    "Norfolk",
    "Normal",
    "Norman",
    "North Charleston",
    "North Las Vegas",
    "North Little Rock",
    "North Miami",
    "North Port",
    "North Richland Hills",
    "Norwalk",
    "Novato",
    "Novi",
    "O'Fallon",
    "Oak Lawn",
    "Oak Park",
    "Oakland",
    "Ocala",
    "Oceanside",
    "Odessa",
    "Ogden",
    "Oklahoma City",
    "Olathe",
    "Omaha",
    "Ontario",
    "Orange",
    "Orem",
    "Orland Park",
    "Orlando",
    "Oshkosh",
    "Overland Park",
    "Owensboro",
    "Oxnard",
    "Palatine",
    "Palm Bay",
    "Palm Beach Gardens",
    "Palm Coast",
    "Palm Desert",
    "Palmdale",
    "Palo Alto",
    "Paramount",
    "Parma",
    "Pasadena",
    "Pasco",
    "Passaic",
    "Paterson",
    "Pawtucket",
    "Peabody",
    "Pearland",
    "Pembroke Pines",
    "Pensacola",
    "Peoria",
    "Perris",
    "Perth Amboy",
    "Petaluma",
    "Pflugerville",
    "Pharr",
    "Philadelphia",
    "Phoenix",
    "Pico Rivera",
    "Pittsburg",
    "Pittsburgh",
    "Placentia",
    "Plainfield",
    "Plano",
    "Plantation",
    "Pleasanton",
    "Plymouth",
    "Pocatello",
    "Pomona",
    "Pompano Beach",
    "Pontiac",
    "Port Arthur",
    "Port Orange",
    "Port St. Lucie",
    "Porterville",
    "Portland",
    "Portsmouth",
    "Providence",
    "Provo",
    "Pueblo",
    "Quincy",
    "Racine",
    "Raleigh",
    "Rancho Cordova",
    "Rancho Cucamonga",
    "Rapid City",
    "Reading",
    "Redding",
    "Redlands",
    "Redmond",
    "Redondo Beach",
    "Redwood City",
    "Reno",
    "Renton",
    "Revere",
    "Rialto",
    "Richardson",
    "Richland",
    "Richmond",
    "Rio Rancho",
    "Riverside",
    "Roanoke",
    "Rochester",
    "Rochester Hills",
    "Rock Hill",
    "Rockford",
    "Rocklin",
    "Rockville",
    "Rocky Mount",
    "Rogers",
    "Rosemead",
    "Roseville",
    "Roswell",
    "Round Rock",
    "Rowlett",
    "Royal Oak",
    "Sacramento",
    "Saginaw",
    "Salem",
    "Salinas",
    "Salt Lake City",
    "Sammamish",
    "San Angelo",
    "San Antonio",
    "San Bernardino",
    "San Buenaventura (Ventura)",
    "San Clemente",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Leandro",
    "San Marcos",
    "San Mateo",
    "San Rafael",
    "San Ramon",
    "Sandy",
    "Sandy Springs",
    "Sanford",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Cruz",
    "Santa Fe",
    "Santa Maria",
    "Santa Monica",
    "Santa Rosa",
    "Santee",
    "Sarasota",
    "Savannah",
    "Schaumburg",
    "Schenectady",
    "Scottsdale",
    "Scranton",
    "Seattle",
    "Shawnee",
    "Shoreline",
    "Shreveport",
    "Simi Valley",
    "Sioux City",
    "Sioux Falls",
    "Skokie",
    "Smyrna",
    "Somerville",
    "South Bend",
    "South Gate",
    "South Jordan",
    "South San Francisco",
    "Southaven",
    "Southfield",
    "Sparks",
    "Spokane",
    "Spokane Valley",
    "Springdale",
    "Springfield",
    "St. Charles",
    "St. Clair Shores",
    "St. Cloud",
    "St. George",
    "St. Joseph",
    "St. Louis",
    "St. Paul",
    "St. Peters",
    "St. Petersburg",
    "Stamford",
    "Sterling Heights",
    "Stockton",
    "Suffolk",
    "Sugar Land",
    "Sunnyvale",
    "Sunrise",
    "Surprise",
    "Syracuse",
    "Tacoma",
    "Tallahassee",
    "Tamarac",
    "Tampa",
    "Taunton",
    "Taylor",
    "Taylorsville",
    "Temecula",
    "Tempe",
    "Temple",
    "Terre Haute",
    "Thornton",
    "Thousand Oaks",
    "Tigard",
    "Tinley Park",
    "Toledo",
    "Topeka",
    "Torrance",
    "Tracy",
    "Trenton",
    "Troy",
    "Tucson",
    "Tulare",
    "Tulsa",
    "Turlock",
    "Tuscaloosa",
    "Tustin",
    "Tyler",
    "Union City",
    "Upland",
    "Utica",
    "Vacaville",
    "Valdosta",
    "Vallejo",
    "Vancouver",
    "Victoria",
    "Victorville",
    "Vineland",
    "Virginia Beach",
    "Visalia",
    "Vista",
    "Waco",
    "Walnut Creek",
    "Waltham",
    "Warner Robins",
    "Warren",
    "Warwick",
    "Washington",
    "Waterbury",
    "Waterloo",
    "Watsonville",
    "Waukegan",
    "Waukesha",
    "Wellington",
    "West Allis",
    "West Covina",
    "West Des Moines",
    "West Haven",
    "West Jordan",
    "West New York",
    "West Palm Beach",
    "West Valley City",
    "Westland",
    "Westminster",
    "Weston",
    "Weymouth Town",
    "Wheaton",
    "White Plains",
    "Whittier",
    "Wichita",
    "Wichita Falls",
    "Wilmington",
    "Winston-Salem",
    "Woodbury",
    "Woodland",
    "Worcester",
    "Wyoming",
    "Yakima",
    "Yonkers",
    "Yorba Linda",
    "Youngstown",
    "Yuba City",
    "Yucaipa",
    "Yuma"
})

CITIES_100K: frozenset[str] = frozenset({
    "Abilene",
    "Akron",
    "Albuquerque",
    "Alexandria",
    "Allentown",
    "Amarillo",
    "Anaheim",
    "Anchorage",
    "Ann Arbor",
    "Antioch",
    "Arlington",
    "Arvada",
    "Athens-Clarke County",
    "Atlanta",
    "Augusta-Richmond County",
    "Aurora",
    "Austin",
    "Bakersfield",
    "Baltimore",
    "Baton Rouge",
    "Beaumont",
    "Bellevue",
    "Berkeley",
    "Billings",
    "Birmingham",
    "Boise City",
    "Boston",
    "Boulder",
    "Bridgeport",
    "Broken Arrow",
    "Brownsville",
    "Buffalo",
    "Burbank",
    "Cambridge",
    "Cape Coral",
    "Carlsbad",
    "Carrollton",
    "Cary",
    "Cedar Rapids",
    "Centennial",
    "Chandler",
    "Charleston",
    "Charlotte",
    "Chattanooga",
    "Chesapeake",
    "Chicago",
    "Chula Vista",
    "Cincinnati",
    "Clarksville",
    "Clearwater",
    "Cleveland",
    "College Station",
    "Colorado Springs",
    "Columbia",
    "Columbus",
    "Concord",
    "Coral Springs",
    "Corona",
    "Corpus Christi",
    "Costa Mesa",
    "Dallas",
    "Daly City",
    "Davenport",
    "Dayton",
    "Denton",
    "Denver",
    "Des Moines",
    "Detroit",
    "Downey",
    "Durham",
    "El Cajon",
    "El Monte",
    "El Paso",
    "Elgin",
    "Elizabeth",
    "Elk Grove",
    "Erie",
    "Escondido",
    "Eugene",
    "Evansville",
    "Everett",
    "Fairfield",
    "Fargo",
    "Fayetteville",
    "Fontana",
    "Fort Collins",
    "Fort Lauderdale",
    "Fort Wayne",
    "Fort Worth",
    "Fremont",
    "Fresno",
    "Frisco",
    "Fullerton",
    "Gainesville",
    "Garden Grove",
    "Garland",
    "Gilbert",
    "Glendale",
    "Grand Prairie",
    "Grand Rapids",
    "Green Bay",
    "Greensboro",
    "Gresham",
    "Hampton",
    "Hartford",
    "Hayward",
    "Henderson",
    "Hialeah",
    "High Point",
    "Hollywood",
    "Honolulu",
    "Houston",
    "Huntington Beach",
    "Huntsville",
    "Independence",
    "Indianapolis",
    "Inglewood",
    "Irvine",
    "Irving",
    "Jackson",
    "Jacksonville",
    "Jersey City",
    "Joliet",
    "Kansas City",
    "Kent",
    "Killeen",
    "Knoxville",
    "Lafayette",
    "Lakeland",
    "Lakewood",
    "Lancaster",
    "Lansing",
    "Laredo",
    "Las Cruces",
    "Las Vegas",
    "Lewisville",
    "Lexington-Fayette",
    "Lincoln",
    "Little Rock",
    "Long Beach",
    "Los Angeles",
    "Louisville",
    "Lowell",
    "Lubbock",
    "Madison",
    "Manchester",
    "McAllen",
    "McKinney",
    "Memphis",
    "Mesa",
    "Mesquite",
    "Miami",
    "Miami Gardens",
    "Midland",
    "Milwaukee",
    "Minneapolis",
    "Miramar",
    "Mobile",
    "Modesto",
    "Montgomery",
    "Moreno Valley",
    "Murfreesboro",
    "Murrieta",
    "Naperville",
    "Nashville",
    "New Haven",
    "New Orleans",
    "New York",
    "Newark",
    "Newport News",
    "Norfolk",
    "Norman",
    "North Charleston",
    "North Las Vegas",
    "Norwalk",
    "Oakland",
    "Oceanside",
    "Odessa",
    "Oklahoma City",
    "Olathe",
    "Omaha",
    "Ontario",
    "Orange",
    "Orlando",
    "Overland Park",
    "Oxnard",
    "Palm Bay",
    "Palmdale",
    "Pasadena",
    "Paterson",
    "Pearland",
    "Pembroke Pines",
    "Peoria",
    "Philadelphia",
    "Phoenix",
    "Pittsburgh",
    "Plano",
    "Pomona",
    "Pompano Beach",
    "Port St. Lucie",
    "Portland",
    "Providence",
    "Provo",
    "Pueblo",
    "Raleigh",
    "Rancho Cucamonga",
    "Reno",
    "Rialto",
    "Richardson",
    "Richmond",
    "Riverside",
    "Rochester",
    "Rockford",
    "Roseville",
    "Round Rock",
    "Sacramento",
    "Salem",
    "Salinas",
    "Salt Lake City",
    "San Antonio",
    "San Bernardino",
    "San Buenaventura (Ventura)",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Mateo",
    "Santa Ana",
    "Santa Clara",
    "Santa Clarita",
    "Santa Maria",
    "Santa Rosa",
    "Savannah",
    "Scottsdale",
    "Seattle",
    "Shreveport",
    "Simi Valley",
    "Sioux Falls",
    "South Bend",
    "Spokane",
    "Springfield",
    "St. Louis",
    "St. Paul",
    "St. Petersburg",
    "Stamford",
    "Sterling Heights",
    "Stockton",
    "Sunnyvale",
    "Surprise",
    "Syracuse",
    "Tacoma",
    "Tallahassee",
    "Tampa",
    "Temecula",
    "Tempe",
    "Thornton",
    "Thousand Oaks",
    "Toledo",
    "Topeka",
    "Torrance",
    "Tucson",
    "Tulsa",
    "Tyler",
    "Vallejo",
    "Vancouver",
    "Victorville",
    "Virginia Beach",
    "Visalia",
    "Waco",
    "Warren",
    "Washington",
    "Waterbury",
    "West Covina",
    "West Jordan",
    "West Palm Beach",
    "West Valley City",
    "Westminster",
    "Wichita",
    "Wichita Falls",
    "Wilmington",
    "Winston-Salem",
    "Worcester",
    "Yonkers"
})
